### ISSUE TITLE
`ERR_REQUIRE_ESM` when using importing in a TypeScript script using `ts-node`

### ISSUE THREAD

**Issue by ariasuni** [PlasmoHQ/edge-addons-api#64]
I get `ERR_REQUIRE_ESM` all the time when trying to use your library with `ts-node` and my TypeScript configuration. It seems to me that your package doesn’t respect the JavaScript ecosystem convention to transpile the code to CommonJS for backward compatibility. It’s also possible to support both at the same time, [according to this answer on StackOverflow](https://stackoverflow.com/questions/74937600/how-to-support-es-modules-and-commonjs-modules-at-the-same-time/75348391#75348391). It would be nice if users of the library wouldn’t have to struggle with the fact that it supports only ESM.

**Comment by louisgv** [comment]
Hey @ariasuni - which nodejs version are you using CJS is a deprecated format and is being phased out due to its bloating bundle size. Please read this thread for more info on the gist of the ecosystem's thought: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

An older version of this package supported CJS, but I'm not sure which one. Although is possible to support both at the same time, it's also very trivial for end user to rebundle ESM as CJS if needed on their side <- this is the benefit of using ESM, we give the power to the end-user of the package. CJS, on the other hand, will not let you do that since it tightly pack everything.

**Comment by ariasuni** [comment]
Thanks for the answer! The problem I had was a package with multiple scripts which are not using ESM, migrating them all just for one new script was annoying. I worked around that by creating a new separated package.
